treewide: import local change
Signed-off-by: oItsMineZ <135024283+oItsMineZ@users.noreply.github.com>

diff --git a/mkimg b/mkimg
--- a/mkimg
+++ b/mkimg
@@ -1,11 +1,20 @@
 #!/bin/bash
-# AIK-Linux/repackimg: repack ramdisk and build image
+# AIK-Linux/RepackImage: Repack Ramdisk and Build Image
 # osm0sis @ xda-developers
+# oItsMineZ @ github
 
-abort() { echo "Error!"; }
+separator () {
+  echo "---------------------------------------------------------"
+}
+
+quotes () {
+  echo "-- $1"
+}
+
+abort() { quotes "Error!"; }
 
 case $1 in
-  --help) echo "usage: repackimg.sh [--local] [--original] [--origsize] [--level <0-9>] [--avbkey <name>] [--forceelf]"; exit 1;
+  --help) quotes "Usage: mkimg [--local] [--original] [--origsize] [--level <0-9>] [--avbkey <name>] [--forceelf]"; exit 1;
 esac;
 
 case $(uname -s) in
@@ -40,7 +49,7 @@ case $plat in
   ;;
   linux)
     cpio=cpio;
-    [ "$(cpio --version | head -n1 | rev | cut -d\  -f1 | rev)" = "2.13" ] && cpiowarning=1;
+    [ "$(cpio --version | head -n1 | rev | cut -d\  -f1 | rev)" = "2.13" ] && cpiowarnings=1;
     statarg="-c %U";
   ;;
 esac;
@@ -53,7 +62,7 @@ chmod -R 755 "$bin" "$aik/"*.sh;
 chmod 644 "$bin/magic" "$bin/androidbootimg.magic" "$bin/boot_signer.jar" "$bin/avb/"* "$bin/chromeos/"*;
 
 if [ -z "$(ls split_img/* 2>/dev/null)" -o ! -e ramdisk ]; then
-  echo "No files found to be packed/built.";
+  quotes "No Files Found to be Packed/Built.";
   abort;
   exit 1;
 fi;
@@ -84,20 +93,19 @@ done;
 
 ramdiskcomp=`cat split_img/*-*ramdiskcomp 2>/dev/null`;
 if [ -z "$(ls ramdisk/* 2>/dev/null)" ] && [ ! "$ramdiskcomp" = "empty" -a ! "$original" ]; then
-  echo "No files found to be packed/built.";
+  quotes "No Files Found to be Packed/Built.";
   abort;
   exit 1;
 fi;
 
-clear;
-echo " ";
-echo "Android Image Kitchen - RepackImg Script";
-echo "by osm0sis @ xda-developers";
-echo " ";
+separator
+quotes "Android Image Kitchen - Repack Image Script";
+quotes "By osm0sis @ xda-developers";
+quotes "Edited by oItsMineZ @ github";
+separator
 
 if [ ! -z "$(ls *-new.* 2>/dev/null)" ]; then
-  echo "Warning: Overwriting existing files!";
-  echo " ";
+  quotes "Warning: Overwriting Existing Files!";
 fi;
 rm -f "*-new.*";
 
@@ -108,16 +116,15 @@ else
 fi;
 
 if [ "$original" ]; then
-  echo "Repacking with original ramdisk...";
+  quotes "Repacking with original ramdisk...";
 elif [ "$ramdiskcomp" = "empty" ]; then
-  echo "Warning: Using empty ramdisk for repack!";
+  quotes "Warning: Using empty ramdisk for repack!";
   compext=.empty;
   touch ramdisk-new.cpio$compext;
 else
-  echo "Packing ramdisk$sumsg...";
-  echo " ";
+  quotes "Packing Ramdisk$sumsg...";
   if [ "$cpiowarning" ]; then
-    echo "Warning: Using cpio 2.13 may result in an unusable repack; downgrade to 2.12 to be safe!";
+    quotes "Warning: Using cpio 2.13 may Result in an Unusable Repack; Downgrade to 2.12 to be Safe!";
     echo " ";
   fi;
   if [ -z "$level" ]; then
@@ -126,7 +133,7 @@ else
       lz4*) level=-9;;
     esac;
   fi;
-  echo "Using compression: $ramdiskcomp$lvltxt";
+  quotes "Using Compression: $ramdiskcomp$lvltxt";
   repackcmd="$ramdiskcomp $level";
   compext=$ramdiskcomp;
   case $ramdiskcomp in
@@ -152,8 +159,9 @@ else
   cd ..;
 fi;
 
-echo " ";
-echo "Getting build information...";
+separator
+quotes "Getting Build Information...";
+separator
 cd split_img;
 imgtype=`cat *-imgtype`;
 case $imgtype in
@@ -161,93 +169,93 @@ case $imgtype in
   AOSP_VNDR) vendor=vendor_;;
   *)
     if [ -f *-kernel ]; then
-      kernel=`ls *-kernel`;              echo "kernel = $kernel";
+      kernel=`ls *-kernel`;              quotes "Kernel: $kernel";
       kernel="split_img/$kernel";
     fi;
   ;;
 esac;
 if [ "$original" ]; then
-  ramdisk=`ls *-*ramdisk.cpio*`;         echo "${vendor}ramdisk = $ramdisk";
+  ramdisk=`ls *-*ramdisk.cpio*`;         quotes "${vendor}Ramdisk: $ramdisk";
   ramdisk="split_img/$ramdisk";
 else
   ramdisk="ramdisk-new.cpio$compext";
 fi;
 case $imgtype in
-  KRNL) rsz=$(wc -c < ../"$ramdisk");    echo "ramdisk_size = $rsz";;
-  OSIP)                                  echo "cmdline = $(cat *-*cmdline)";;
+  KRNL) rsz=$(wc -c < ../"$ramdisk");    quotes "Ramdisk Size: $rsz";;
+  OSIP)                                  quotes "CMDline: $(cat *-*cmdline)";;
   U-Boot)
-    name=`cat *-name`;                   echo "name = $name";
+    name=`cat *-name`;                   quotes "Name: $name";
     uarch=`cat *-arch`;
     os=`cat *-os`;
     type=`cat *-type`;
-    comp=`cat *-comp`;                   echo "type = $uarch $os $type ($comp)";
+    comp=`cat *-comp`;                   quotes "Type: $uarch $os $type ($comp)";
     [ "$comp" = "uncompressed" ] && comp=none;
-    addr=`cat *-addr`;                   echo "load_addr = $addr";
-    ep=`cat *-ep`;                       echo "entry_point = $ep";
+    addr=`cat *-addr`;                   quotes "Load ADDR: $addr";
+    ep=`cat *-ep`;                       quotes "Entry Point: $ep";
   ;;
   *)
     if [ -f *-second ]; then
-      second=`ls *-second`;              echo "second = $second";
+      second=`ls *-second`;              quotes "Second: $second";
       second=(--second "split_img/$second");
     fi;
     if [ -f *-dtb ]; then
-      dtb=`ls *-dtb`;                    echo "dtb = $dtb";
+      dtb=`ls *-dtb`;                    quotes "DTB: $dtb";
       dtb=(--dtb "split_img/$dtb");
     fi;
     if [ -f *-recovery_dtbo ]; then
-      recoverydtbo=`ls *-recovery_dtbo`; echo "recovery_dtbo = $recoverydtbo";
+      recoverydtbo=`ls *-recovery_dtbo`; quotes "Recovery DTBO: $recoverydtbo";
       recoverydtbo=(--recovery_dtbo "split_img/$recoverydtbo");
     fi;
     if [ -f *-*cmdline ]; then
       cmdname=`ls *-*cmdline`;
-      cmdline=`cat *-*cmdline`;          echo "${vendor}cmdline = $cmdline";
+      cmdline=`cat *-*cmdline`;          quotes "${vendor}CMDline: $cmdline";
       cmd=("split_img/$cmdname"@cmdline);
     fi;
     if [ -f *-board ]; then
-      board=`cat *-board`;               echo "board = $board";
+      board=`cat *-board`;               quotes "Board: $board";
     fi;
     if [ -f *-base ]; then
-      base=`cat *-base`;                 echo "base = $base";
+      base=`cat *-base`;                 quotes "Base: $base";
     fi;
     if [ -f *-pagesize ]; then
-      pagesize=`cat *-pagesize`;         echo "pagesize = $pagesize";
+      pagesize=`cat *-pagesize`;         quotes "Page Size: $pagesize";
     fi;
     if [ -f *-kernel_offset ]; then
-      kerneloff=`cat *-kernel_offset`;   echo "kernel_offset = $kerneloff";
+      kerneloff=`cat *-kernel_offset`;   quotes "Kernel Offset: $kerneloff";
     fi;
     if [ -f *-ramdisk_offset ]; then
-      ramdiskoff=`cat *-ramdisk_offset`; echo "ramdisk_offset = $ramdiskoff";
+      ramdiskoff=`cat *-ramdisk_offset`; quotes "Ramdisk Offset: $ramdiskoff";
     fi;
     if [ -f *-second_offset ]; then
-      secondoff=`cat *-second_offset`;   echo "second_offset = $secondoff";
+      secondoff=`cat *-second_offset`;   quotes "Second Offset: $secondoff";
     fi;
     if [ -f *-tags_offset ]; then
-      tagsoff=`cat *-tags_offset`;       echo "tags_offset = $tagsoff";
+      tagsoff=`cat *-tags_offset`;       quotes "Tags Offset: $tagsoff";
     fi;
     if [ -f *-dtb_offset ]; then
-      dtboff=`cat *-dtb_offset`;         echo "dtb_offset = $dtboff";
+      dtboff=`cat *-dtb_offset`;         quotes "DTB Offset: $dtboff";
     fi;
     if [ -f *-os_version ]; then
-      osver=`cat *-os_version`;          echo "os_version = $osver";
+      osver=`cat *-os_version`;          quotes "OS Version: $osver";
     fi;
     if [ -f *-os_patch_level ]; then
-      oslvl=`cat *-os_patch_level`;      echo "os_patch_level = $oslvl";
+      oslvl=`cat *-os_patch_level`;      quotes "OS Patch Level: $oslvl";
     fi;
     if [ -f *-header_version ]; then
-      hdrver=`cat *-header_version`;     echo "header_version = $hdrver";
+      hdrver=`cat *-header_version`;     quotes "Header Version: $hdrver";
     fi;
     if [ -f *-hashtype ]; then
-      hashtype=`cat *-hashtype`;         echo "hashtype = $hashtype";
+      hashtype=`cat *-hashtype`;         quotes "Hashtype: $hashtype";
       hashtype="--hashtype $hashtype";
     fi;
     if [ -f *-dt ]; then
       dttype=`cat *-dttype`;
-      dt=`ls *-dt`;                      echo "dt = $dt";
+      dt=`ls *-dt`;                      quotes "DT: $dt";
       rpm=("split_img/$dt",rpm);
       dt=(--dt "split_img/$dt");
     fi;
     if [ -f *-unknown ]; then
-      unknown=`cat *-unknown`;           echo "unknown = $unknown";
+      unknown=`cat *-unknown`;           quotes "Unknown = $unknown";
     fi;
     if [ -f *-header ]; then
       header=`ls *-header`;
@@ -259,10 +267,10 @@ cd ..;
 
 if [ -f split_img/*-mtktype ]; then
   mtktype=`cat split_img/*-mtktype`;
-  echo " ";
-  echo "Generating MTK headers...";
-  echo " ";
-  echo "Using ramdisk type: $mtktype";
+  separator
+  quotes "Generating MTK Headers...";
+  separator
+  quotes "Using Ramdisk Type: $mtktype";
   "$bin/$arch/mkmtkhdr" --kernel "$kernel" --$mtktype "$ramdisk" >/dev/null;
   if [ ! $? -eq "0" ]; then
     abort;
@@ -275,7 +283,7 @@ if [ -f split_img/*-mtktype ]; then
 fi;
 
 if [ -f split_img/*-sigtype ]; then
-  outname=unsigned-new.img;
+  outname=boot-unsigned.img;
 else
   outname=image-new.img;
 fi;
@@ -283,15 +291,15 @@ fi;
 [ "$dttype" = "ELF" ] && repackelf=1;
 if [ "$imgtype" = "ELF" ] && [ ! "$header" -o ! "$repackelf" ]; then
   imgtype=AOSP;
-  echo " ";
-  echo "Warning: ELF format without RPM detected; will be repacked using AOSP format!";
+  separator
+  quotes "Warning: ELF Format Without RPM Detected; will be Repacked using AOSP Format!";
 fi;
 
-echo " ";
-echo "Building image...";
-echo " ";
-echo "Using format: $imgtype";
-echo " ";
+separator
+quotes "Building Image...";
+separator
+quotes "Using Format: $imgtype";
+separator
 case $imgtype in
   AOSP_VNDR) "$bin/$arch/mkbootimg" --vendor_ramdisk "$ramdisk" "${dtb[@]}" --vendor_cmdline "$cmdline" --board "$board" --base $base --pagesize $pagesize --kernel_offset $kerneloff --ramdisk_offset $ramdiskoff --tags_offset $tagsoff --dtb_offset $dtboff --os_version "$osver" --os_patch_level "$oslvl" --header_version $hdrver --vendor_boot $outname;;
   AOSP) "$bin/$arch/mkbootimg" --kernel "$kernel" --ramdisk "$ramdisk" "${second[@]}" "${dtb[@]}" "${recoverydtbo[@]}" --cmdline "$cmdline" --board "$board" --base $base --pagesize $pagesize --kernel_offset $kerneloff --ramdisk_offset $ramdiskoff --second_offset "$secondoff" --tags_offset "$tagsoff" --dtb_offset "$dtboff" --os_version "$osver" --os_patch_level "$oslvl" --header_version "$hdrver" $hashtype "${dt[@]}" -o $outname;;
@@ -314,7 +322,7 @@ case $imgtype in
     esac;
     "$bin/$arch/mkimage" -A $uarch -O $os -T $type -C $comp -a $addr -e $ep -n "$name" -d "$part0""${part1[@]}" $outname >/dev/null;
   ;;
-  *) echo " "; echo "Unsupported format."; abort; exit 1;;
+  *) echo " "; quotes "Unsupported Format."; abort; exit 1;;
 esac;
 if [ ! $? -eq "0" ]; then
   abort;
@@ -331,25 +339,25 @@ if [ -f split_img/*-sigtype ]; then
   if [ -f split_img/*-blobtype ]; then
     blobtype=`cat split_img/*-blobtype`;
   fi;
-  echo "Signing new image...";
-  echo " ";
-  echo "Using signature: $sigtype $avbtype$avbtxt$blobtype";
+  quotes "Signing New Image...";
+  separator
+  quotes "Using Signature: $sigtype $avbtype$avbtxt$blobtype";
   [ ! "$avbkey" ] && avbkey="$bin/avb/verity";
-  echo " ";
+  separator
   case $sigtype in
-    AVBv1) java -jar "$bin/boot_signer.jar" /$avbtype unsigned-new.img "$avbkey.pk8" "$avbkey.x509."* image-new.img 2>/dev/null;;
+    AVBv1) java -jar "$bin/boot_signer.jar" /$avbtype boot-unsigned.img "$avbkey.pk8" "$avbkey.x509."* image-new.img 2>/dev/null;;
     BLOB)
       awk 'BEGIN { printf "-SIGNED-BY-SIGNBLOB-\00\00\00\00\00\00\00\00" }' > image-new.img;
-      "$bin/$arch/blobpack" blob.tmp $blobtype unsigned-new.img >/dev/null;
+      "$bin/$arch/blobpack" blob.tmp $blobtype boot-unsigned.img >/dev/null;
       cat blob.tmp >> image-new.img;
       rm -f blob.tmp;
     ;;
-    CHROMEOS) "$bin/$arch/futility" vbutil_kernel --pack image-new.img --keyblock "$bin/chromeos/kernel.keyblock" --signprivate "$bin/chromeos/kernel_data_key.vbprivk" --version 1 --vmlinuz unsigned-new.img --bootloader "$bin/chromeos/empty" --config "$bin/chromeos/empty" --arch arm --flags 0x1;;
+    CHROMEOS) "$bin/$arch/futility" vbutil_kernel --pack image-new.img --keyblock "$bin/chromeos/kernel.keyblock" --signprivate "$bin/chromeos/kernel_data_key.vbprivk" --version 1 --vmlinuz boot-unsigned.img --bootloader "$bin/chromeos/empty" --config "$bin/chromeos/empty" --arch arm --flags 0x1;;
     DHTB)
-      "$bin/$arch/dhtbsign" -i unsigned-new.img -o image-new.img >/dev/null;
+      "$bin/$arch/dhtbsign" -i boot-unsigned.img -o image-new.img >/dev/null;
       rm -f split_img/*-tailtype 2>/dev/null;
     ;;
-    NOOK*) cat split_img/*-master_boot.key unsigned-new.img > image-new.img;;
+    NOOK*) cat split_img/*-master_boot.key boot-unsigned.img > image-new.img;;
   esac;
   if [ ! $? -eq "0" ]; then
     abort;
@@ -359,26 +367,26 @@ fi;
 
 if [ -f split_img/*-lokitype ]; then
   lokitype=`cat split_img/*-lokitype`;
-  echo "Loki patching new image...";
-  echo " ";
-  echo "Using type: $lokitype";
-  echo " ";
+  quotes "Loki Patching New Image...";
+  separator
+  quotes "Using Type: $lokitype";
+  separator
   mv -f image-new.img unlokied-new.img;
   if [ -f aboot.img ]; then
     "$bin/$arch/loki_tool" patch $lokitype aboot.img unlokied-new.img image-new.img >/dev/null;
     if [ ! $? -eq "0" ]; then
-      echo "Patching failed.";
+      quotes "Patching Failed!";
       abort;
       exit 1;
     fi;
   else
-    echo "Device aboot.img required in script directory to find Loki patch offset.";
+    quotes "Device aboot.img Required in Script Directory to Find Loki Patch Offset.";
     abort;
     exit 1;
   fi;
 elif [ -f split_img/*-microloader.bin ]; then
-  echo "Amonet patching new image...";
-  echo " ";
+  quotes "Amonet Patching New Image...";
+  separator
   cp -f image-new.img unamonet-new.img;
   cp -f split_img/*-microloader.bin microloader.tmp;
   dd bs=1024 count=1 conv=notrunc if=unamonet-new.img of=head.tmp 2>/dev/null;
@@ -389,10 +397,10 @@ fi;
 
 if [ -f split_img/*-tailtype ]; then
   tailtype=`cat split_img/*-tailtype`;
-  echo "Appending footer...";
-  echo " ";
-  echo "Using type: $tailtype";
-  echo " ";
+  quotes "Appending Footer...";
+  separator
+  quotes "Using Type: $tailtype";
+  separator
   case $tailtype in
     Bump) awk 'BEGIN { printf "\x41\xA9\xE4\x67\x74\x4D\x1D\x1B\xA4\x29\xF2\xEC\xEA\x65\x52\x79" }' >> image-new.img;;
     SEAndroid) printf 'SEANDROIDENFORCE' >> image-new.img;;
@@ -401,12 +409,12 @@ fi;
 
 if [ "$origsize" -a -f split_img/*-origsize ]; then
   filesize=`cat split_img/*-origsize`;
-  echo "Padding to original size...";
-  echo " ";
+  quotes "Padding to Original Size...";
+  separator
   cp -f image-new.img unpadded-new.img;
   truncate -s $filesize image-new.img;
 fi;
 
-echo "Done!";
+quotes "Done!";
 exit 0;
 
